# Generated by Django 5.2.8 on 2025-11-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FipeCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fipe_id', models.CharField(max_length=255)),
                ('brand', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
                ('year', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(max_length=255)),
                ('gear_type', models.CharField(max_length=255)),
                ('engine_size', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Fipe Car',
                'verbose_name_plural': 'Fipe Cars',
                'db_table': 'tb_fipe_car',
            },
        ),
    ]
