# Generated by Django 5.2.8 on 2025-11-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fipe_car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fipecar',
            name='engine_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fipecar',
            name='price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='fipecar',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
